name: mocc
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  change_app_package_name: ^1.5.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  go_router: ^17.0.1
  graphql_flutter: ^5.2.1
  msal_auth: ^3.3.0
  msal_js: ^2.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon/
    - assets/lotties/
    - assets/translations
